name = "irlid-api"
main = "src/index.js"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
CORS_ORIGIN = "https://bunhead.github.io"

[[d1_databases]]
binding = "DB"
database_name = "irlid-db"
database_id = "6eb1c15e-a975-4ad4-bc18-fe36dd96f828"
