name = "irlid-api-org"
main = "src/index.js"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
CORS_ORIGIN = "https://irlid.co.uk"

[[d1_databases]]
binding = "DB"
database_name = "irlid-db-org"
database_id = "484dad86-e75c-412e-9423-ca0bb27cdcb8"
